### ISSUE TITLE
Srediti Backup na ovim podserverima

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#491]
https://prnt.sc/UrY9jnHZbSHv

određenim podserverima na MNB treba srediti automatski backup na disk

automatski backup na disk je dodatna mera zaštite podataka koju imamo na svim podserverima kako bi pored običnog backupa koji vršimo redovno ali i backupa nekih podservera na fleš (Pre Lapute i SMP) obezbedili dodatno skladištenje na disk koji je nezavistan od bilo kog igrača ili lokacije

**Comment by PiweeX** [comment]
ubačeno na nekim serverima

**Comment by PiweeX** [comment]
[22:12:31 WARN]: ratismal.drivebackup.DriveBackup.lib.JSONException: A JSONObject text must begin with '{' at 2 [character 1 line 2]
[22:12:31 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.JSONTokener.syntaxError(JSONTokener.java:507)
[22:12:31 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.<init>(JSONObject.java:222)
[22:12:31 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.<init>(JSONObject.java:406)
[22:12:31 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.Authenticator.authenticateUser(Authenticator.java:121)
[22:12:31 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.handler.commandHandler.CommandHandler.onCommand(CommandHandler.java:83)
[22:12:31 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:12:31 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:12:31 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[22:12:31 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[22:12:31 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:513)
[22:12:31 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[22:12:31 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[22:12:31 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1228)
[22:12:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318)
[22:12:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by PiweeX** [comment]
dakle postojao je problem da na nekim podserverima automatski backup na naše privatne diskove nije namešten

krenuli smo u nameštanje i prikazivao je error od gore, najbolji način da se to reši bio je da se od svud pobriše i da se ponovo postavi sa novom verzijom i izmenjenom konfiguracijom

HogRealms - Balkanski Builderi (BTE Balkan)
HogRealms - Platforme (bDrowned)
HogRealms - Iznad Lapute (djonmla I djovani)
HogRealms - SMP 2024 Unutar Lapute (PSIHO)
HogRealms - Platforme Dev (bDrowned)
HogRealms - Borbe za Laputu
HogRealms - Developer Mod (DAO)
HogRealms - Lobby (DAO)
HogRealms - Pre Lapute (Cone) 2

su serveri koji su od večeras obezbeđeni, mnogi odatle su već i bili obezbeđeni na tim diskovima a i dodatno na skladištu ali ovako se osećam sigurnije kad znam da je sve gotovo stalno backupovano

prvi sledeći backup kad su i zakazani će rešiti ovaj problem od kog nisam mogao da spavam iskreno xd
