### ISSUE TITLE
Hogo Studios tiket bot fix

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#508]
**Popraviti hogostudios bota sutra, napraviti dakle novog na skladištu al ne core nego običnog tiket od džonija**

**Comment by PiweeX** [comment]
FIXANO!

**Comment by PiweeX** [comment]
ima problem sa transcriptom, 

[ERROR] TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /home/container/utils/createTranscript.js:38:41
    at Array.map (<anonymous>)
    at htmlTranscript (/home/container/utils/createTranscript.js:35:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InteractionCollector.<anonymous> (/home/container/events/custom/ticketClose.js:146:11)

prijavljeno dzoniju resicemo
