### ISSUE TITLE
bot za mentalno zdravlje na MNB discordu

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#511]
ubačen, uskoro stiže

**Comment by PiweeX** [comment]
ubačeni fajlovi još da se napravi bot

**Comment by PiweeX** [comment]
PiweeeX — Yesterday at 11:16 PM
e, imam problem oko transcripta
[ERROR] TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /home/container/utils/createTranscript.js:38:41
    at Array.map (<anonymous>)
    at htmlTranscript (/home/container/utils/createTranscript.js:35:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InteractionCollector.<anonymous> (/home/container/events/custom/ticketClose.js:146:11)
pise to kad god idem da transcriptam neki tiket
NIDZA — Yesterday at 11:30 PM
Skini samo opet bota i zameni taj file
utils/createTranscript.js
Malopre sam reupload
PiweeeX — Today at 12:02 AM
radi sve kako treba sad hvala

**Comment by PiweeX** [comment]
zamenjeno i na ovom što će biti

**Comment by PiweeX** [comment]
sredjen kanal

**Comment by PiweeX** [comment]
Premešta se na forum
